first pass at adding tooling for repo standardization
usertesting/github-standardization pull request #1
Opened 2021-11-15 22:33 UTC by relwell

Adds some tooling to create a PR integrating blackduck with existing repos, and some additional stuff to enforce branch protection.

Coming up next will be some workflows to support this for arbitrary projects.

2021-11-15 22:33 UTC, relwell commented on files/blackduck.yml
> +name: Blackduck Check
This gets added to other projects to enforce blackduck

2021-11-15 22:33 UTC, relwell commented on ghs.py
> +def standardize_branch_protection(branch: Branch):
I ran this from the iPython console and got some decent branch protection settings for this repo 😲

2021-11-15 22:34 UTC, relwell commented on ghs.py
> +        return get_github_client().get_organization(org).create_repo(name)
This is actually how I created the repo you're looking at now!

2021-11-16 09:39 UTC, DanK-UT approved these changes
Interested to know how this might work

2021-11-16 09:58 UTC, andrewphilp-ut commented
This is cool, I'd love to see us standardising GitHub repo configuration. Keen to know if you had considered the GitHub TF [provider](https://registry.terraform.io/providers/integrations/github/latest/docs) to set the repo config and then use the script for BlackDuck? Doesn't look like they have a TF provider unfortunately.

2021-11-16 10:07 UTC, DanK-UT commented on ghs.py
> +        bp.required_pull_request_reviews.required_approving_review_count = 2
I'd like to default this to 1 if possible. Happy for a discussion.

2021-11-16 14:03 UTC, relwell commented on ghs.py
> +        bp.required_pull_request_reviews.required_approving_review_count = 2
These rules match our [compliance requirements](https://user-testing.atlassian.net/wiki/spaces/HELIOS/pages/1252917534/PANDE+Change+Management+2.7). Not all projects may be exposed to them, but this project is targeted to ones that are.

2021-11-16 14:06 UTC, relwell commented
@andrewphilp-ut I have looked at the GitHub terraform provider. There are definitely some pragmatic challenges related to implementing it across the board. Enforcing its use may result in turning O&I into more of a service desk than we'd like. OTOH, if we can provide a script that says, "point this job at the repo you just created",  we should get broader self-service adoption.

2021-11-16 16:03 UTC, dcarter-ut approved these changes
looks good.

2021-11-16 16:03 UTC, dcarter-ut commented on ghs.py
> +        bp.required_pull_request_reviews.required_approving_review_count = 2
parameterized, but defaults to `2`?

2021-11-17 15:10 UTC, jonworek requested changes

2021-11-17 15:10 UTC, jonworek commented on files/blackduck.yml
> +          args: --detect.risk.report.pdf=true
I think it's likely that projects are going to need to customize the arguments provided to synopsys detect. How might we do that?

2021-11-17 15:10 UTC, jonworek commented on files/blackduck.yml
> +      - "*"
same comment as here: https://github.com/usertesting/metering/pull/298/files#r751327502

> You'd need to set the scan type to RAPID for non-master/main branches. Otherwise the scan results from the full scans on all branches would overwhelm BD's system.

2021-11-17 15:10 UTC, jonworek commented on files/blackduck.yml
> +  pull_request:
I believe we need to be running rapid scans on every push. Not just when the PR is opened, lest a new dependency sneak in on a commit after the PR is opened.

2021-11-17 15:14 UTC, jonworek commented on files/blackduck.yml
> +          version: 7
When we need to update to an eventual version 8, how are the changes applied across all repos that include this workflow? 

I don't have a full understanding of how this setup works, but I'm assuming you're copying this file into a project and committing it, right? Does that only happen on create of a new repo?

2021-11-17 15:19 UTC, jonworek commented on ghs.py
> +import json
I've been noticing a lot of python code being produced for various things that are being created lately that are coming out of internal tools / opsinfra, such as the recent domain mapping work. Is that the language that y'all have standardized on for tooling like this?

Are you expecting people outside of those teams, such as devops champions, to contribute to this code?

For me personally, not knowing python, it would be a barrier for me to be able to contribute changes or review the code properly. Do you see this being an issue for pande-at-large?

2021-11-17 15:25 UTC, relwell commented on files/blackduck.yml
> +          args: --detect.risk.report.pdf=true
Once the PR is made, we can either customize it by checking out the branch and pushing, or committing the PR itself and making additional modifications as necessary.

2021-11-17 15:27 UTC, relwell commented on files/blackduck.yml
> +  pull_request:
From what I can tell this will run on each push to a PR, but I'll double check and get back to you.

2021-11-17 15:28 UTC, relwell commented on files/blackduck.yml
> +          version: 7
This is to add into existing projects. If we need to do an across-the-board update, we can implement a similar approach to what you see in the Python code, where we would check and see if the file that had been previously created exists, and then edit the line with `version: 7` to be `version: 8`.

2021-11-17 15:32 UTC, relwell commented on ghs.py
> +import json
I wouldn't expect DevOps Champions to necessarily need to support Python-based code; in fact, using it is an enablement methodology for the team itself. Python's a great scripting language for DevOps work, and more of the talent pool can support Python scripting than anything else.

Other parts of PANDE, like the Data Platform, already use Python, so there is a bit of a precedent.

The interface for this particular library will ultimately be actions that we will be able to train other teams on interacting with, the same way you might do with a Jenkins deployment.

2021-11-19 13:50 UTC, relwell commented on files/blackduck.yml
> +          args: --detect.risk.report.pdf=true
@jonworek I've looked into this some more, and one of the pull request event types that triggers the behavior by default is `synchronize`, which is run any time someone updates a PR by pushing a new commit to the branch in question.

2021-11-22 13:44 UTC, relwell commented
@jonworek can you review the changes made to the blackduck bit and let me know if it meets what you're looking for?

2021-11-22 17:51 UTC, jstuart1 approved these changes

2021-11-22 17:53 UTC, merged